from __future__ import annotations

from typing import Any, Dict, List


class MockLLMClient:
    def plan(
        self,
        profile: Dict[str, Any],
        schema: Dict[str, Any],
        candidates: Dict[str, Any],
        user_intent: str,
    ) -> Dict[str, Any]:
        task_candidates = candidates.get("task_candidates", [])
        task = task_candidates[0]["task_type"] if task_candidates else "eda"
        structure = candidates.get("data_structure", {}).get("data_structure", "flat_iid")
        use_mixed = bool(candidates.get("must_use_mixed_effect", False))
        target_candidates = candidates.get("target_candidates", [])
        group_col = None
        schema_groups = candidates.get("data_structure", {}).get("signals", {}).get("schema_group_cols", [])
        if schema_groups:
            group_col = schema_groups[0]
        elif profile.get("group_candidates"):
            group_col = profile["group_candidates"][0]

        return {
            "task_type": task,
            "data_structure": structure,
            "target_column": target_candidates[0] if target_candidates else None,
            "only_eda": task == "eda",
            "use_mixed_effect": use_mixed,
            "group_column": group_col,
            "time_column": profile.get("time_columns", [None])[0] if profile.get("time_columns") else None,
            "feature_strategy": {"encoding": "auto", "scaling": "standard"},
            "modeling_strategy": {"baseline_models": ["default"]},
            "evaluation_strategy": {"metrics": "auto"},
            "reasoning": ["generated by mock llm"],
        }

    def interpret_stage(self, stage: str, stage_result: Dict[str, Any]) -> Dict[str, Any]:
        return {
            "key_findings": [f"{stage} completed", f"actions={len(stage_result.get('actions', []))}"],
            "risks": [],
            "next_step": "continue",
        }

    def answer(self, question: str, artifact_summaries: List[Dict[str, Any]], final_summary: str) -> str:
        return f"Mock answer: {question}\nSummary: {final_summary}"

